baseURL = 'https://wettis.github.io/'
languageCode = 'en-us'
theme = "JuiceBar"
title = "Wettis Blog"

[params]
author = "Wettis"
description = "This is my blog"
authorImage = "/images/profile.jpg"
paginate = 5
Title = "Wettis"
content = "I'm Wettis, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "/images/avatar.png"

# 添加新的社交图标
# 更多社交图标可以在JuiceBar\layouts\partials\svg.html中找到
[[params.social]]
name = "Github"
url = "https://github.com/Wettis"
#[[params.social]]
#name = "telegram"
#url = "https://t.me/Hotjuice"
#[[params.social]]
#name = "twitter"
#url = "https://twitter.com/hotjuicee"
#[[params.social]]
#name = "email"
#url = "mailto:hotjuicew@outlook.com"
#[[params.social]]
#name = "instagram"
#url = "your_url"
#[[params.social]]
#name = "mastodon"
#url = "your_url"
#[[params.social]]
#name = "reddit"
#url = "your_url"
#[[params.social]]
#name = "stackoverflow"
#url = "your_url"

[taxonomies]
category = "categories"
tag = "tags"

# 添加新的导航链接
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

# 如果使用giscus评论系统
#[params.giscus]
#repo = "ENTER REPO HERE"
#repoID = "ENTER REPO ID HERE"
#category = "ENTER CATEGORY NAME HERE"
#categoryID = "ENTER CATEGORY ID HERE"
#mapping = "og:title"
#reactionsEnabled = "1"
#emitMetadata = "0"
#inputPosition = "bottom"
#lang = "en"
#loading = "lazy"

#用于输出文档的设置（必须的）
[outputs]
home = ["HTML", "RSS", "JSON"]